# -*- coding: utf-8 -*-
"""2.Searching Techniques.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mLB2onxOeshQ8mSdKOMScwdd2l3iWio9

Searching Techniques can broadly be classified into Uninformed Search (Brute Force) and Informed Search (Heuristics).
Explain the following informed search techniques and possible applications:

#(i)                  Greedy Best First Search
"""

import heapq  #heapq priority queue. It always gives back the item with the smallest value first (lowest h(n) first

graph={
    'S':['A','B'],
    'A':['C'],
    'B':['C'],
    'C':['G'],
    'D':[],
    'G':[],
}

h={'S':10,'A':7,'B':4,'C':2,'D':6,'G':0}
#Heuristic h(n):

"""#   Greedy Best First Search"""



def greedy_bfs(start,goal):
  open_list = [(h[start], start, [start])]  #(h value,node,path so far)-nodes that are need to explore
  visited=set()
  while open_list:
    _, node ,path =heapq.heappop(open_list) #heappop removes the entry with the lowest h value
    if node==goal:
      return path
    if node in visited:
      continue
    visited.add(node)
    for neighbour in graph[node]:
      if neighbour not in visited:
        heapq.heappush(open_list,(h[neighbour],neighbour,path+[neighbour]))
  return None
path=greedy_bfs('S','G')
print("Path :" ,"->".join(path) if path else "No path")



"""#(ii)                Best-First Search"""

import heapq

graph = {
    'S': ['A', 'B'],
    'A': ['C'],
    'B': ['C'],
    'C': ['G'],
    'D': [],
    'G': [],
}

# Heuristic h(n): estimated distance to goal G
h = {'S': 10, 'A': 7, 'B': 4, 'C': 2, 'D': 6, 'G': 0}

def best_first_search(start,goal):
  open_list=[(h[start],start,[start])]
  visited = set()
  while open_list:
    _,node,path=heapq.heappop(open_list)
    if node ==goal:
      return path
    if node in visited:
      continue
    visited.add(node)
    for neighbour in graph[node]:
      if neighbour not in visited:
        heapq.heappush(open_list,(h[neighbour],neighbour,path+[neighbour]))
  return None
path = best_first_search('S', 'G')
print("Path","->".join(path if path else "NO path"))

"""#(iii) Dijkstra's Algorithm"""

graph = {
    'S': {'A': 1, 'B': 4},
    'A': {'C': 2},
    'B': {'C': 1},
    'C': {'G': 3},
    'D': {},
    'G': {},
}

def dijkstra(start,goal):
  open_list=[(0,start,[start])]
  visited =set()
  while open_list:
    cost,node,path =heapq.heappop(open_list)
    if node==goal:
      return cost,path
    if node in visited:
      continue
    visited.add(node)
    for neighbor,weight in graph[node].items():
      if neighbor not in visited:
        heapq.heappush(open_list,(cost+weight,neighbor,path+[neighbor]))
  return None,None
cost, path= dijkstra('S','G')
if path:
  print("Path","->".join(path),"total cost",cost)
else:
  print("No path")

"""#(iv)  A* algorithm"""

import heapq
# Heuristic h(n): estimated cost from each node to goal G
h = {'S': 5, 'A': 4, 'B': 3, 'C': 2, 'D': 6, 'G': 0}

def a_star(start, goal):
    open_list = [(h[start], 0, start, [start])]   # (f, g, node, path)
    visited = set()
    while open_list:
        f, g, node, path = heapq.heappop(open_list)   # lowest f = g + h first
        if node == goal:
            return g, path
        if node in visited:
            continue
        visited.add(node)
        for neighbour, weight in graph[node].items():
            if neighbour not in visited:
                new_g = g + weight
                heapq.heappush(open_list, (new_g + h[neighbour], new_g, neighbour, path + [neighbour]))
    return None, None

cost, path = a_star('S', 'G')
if path:
    print("Path:", "->".join(path), "| Total cost:", cost)
else:
    print("No path")

"""#(v)Beam search

"""

def beam_search(start, goal, k=2):
    beam = [(h[start], start, [start])]
    while beam:
        candidates = []
        for _, node, path in beam:
            if node == goal:
                return path
            for nb in graph[node]:
                if nb not in path:
                    candidates.append((h[nb], nb, path + [nb]))
        beam = sorted(candidates)[:k]      # keep only the k best
    return None

path = beam_search("S", "G", k=2)
cost = sum(graph[a][b] for a, b in zip(path, path[1:]))
print("Path:", "->".join(path), "| Total cost:", cost)





"""#(vi)RBFS

"""

def rbfs(node, g, path, f_limit):
    if node == "G":
        return path, g
    succ = []
    for nb, w in graph[node].items():
        if nb not in path:
            ng = g + w
            succ.append([max(ng + h[nb], g + h[node]), ng, nb])
    if not succ:
        return None, float("inf")
    while True:
        succ.sort()
        best = succ[0]
        if best[0] > f_limit:
            return None, best[0]
        alt = succ[1][0] if len(succ) > 1 else float("inf")
        result, val = rbfs(best[2], best[1], path + [best[2]], min(f_limit, alt))
        if result is not None:
            return result, val
        best[0] = val                      # back up the best f found

path, cost = rbfs("S", 0, ["S"], float("inf"))
print("Path:", "->".join(path), "Total cost:", cost)



"""#(vii) IDA*"""

def ida_star(start, goal):
    path = [start]

    def search(g, threshold):
        node = path[-1]
        f = g + h[node]
        if f > threshold:
            return f, False
        if node == goal:
            return g, True
        minimum = float("inf")
        for nb, w in graph[node].items():
            if nb not in path:
                path.append(nb)
                t, found = search(g + w, threshold)
                if found:
                    return t, True
                minimum = min(minimum, t)
                path.pop()
        return minimum, False

    threshold = h[start]
    while True:
        t, found = search(0, threshold)
        if found:
            return t, path
        if t == float("inf"):
            return None, None
        threshold = t                      # raise the f-limit

cost, path = ida_star("S", "G")
print("Path:", "->".join(path), "Total cost:", cost)



"""#(viii) Weighted A*"""

def weighted_a_star(start, goal, w=2):
    open_list = [(w * h[start], 0, start, [start])]   # (f, g, node, path)
    visited = set()
    while open_list:
        f, g, node, path = heapq.heappop(open_list)
        if node == goal:
            return g, path
        if node in visited:
            continue
        visited.add(node)
        for nb, cost in graph[node].items():
            if nb not in visited:
                ng = g + cost
                heapq.heappush(open_list, (ng + w * h[nb], ng, nb, path + [nb]))
    return None, None

cost, path = weighted_a_star("S", "G", w=2)
print("Path:", "->".join(path), "| Total cost:", cost)